spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securecapita
    username:sys
    password:123
    driver-class-name:org.postgresql.Driver
  jpa:
    database-platform:org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:update
